// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0I8Tm8Su06KoqrnxD7hMeIw11NEcuhNg',
    appId: '1:75070219171:web:5a66e63435730aefdff016',
    messagingSenderId: '75070219171',
    projectId: 'fir-auth-5a5b0',
    authDomain: 'fir-auth-5a5b0.firebaseapp.com',
    storageBucket: 'fir-auth-5a5b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqO0ug2oa89zigaLNYlgXvSQFdzrWicXg',
    appId: '1:75070219171:android:77328c2c24b049d6dff016',
    messagingSenderId: '75070219171',
    projectId: 'fir-auth-5a5b0',
    storageBucket: 'fir-auth-5a5b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcCdbhlywkUs9Fz7iwDJpIvcoPg7cvHH8',
    appId: '1:75070219171:ios:c87da172c136b35bdff016',
    messagingSenderId: '75070219171',
    projectId: 'fir-auth-5a5b0',
    storageBucket: 'fir-auth-5a5b0.appspot.com',
    iosClientId: '75070219171-mu04hu2h3q5ud3ki15v2o1ld2ojj7ero.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcCdbhlywkUs9Fz7iwDJpIvcoPg7cvHH8',
    appId: '1:75070219171:ios:c87da172c136b35bdff016',
    messagingSenderId: '75070219171',
    projectId: 'fir-auth-5a5b0',
    storageBucket: 'fir-auth-5a5b0.appspot.com',
    iosClientId: '75070219171-mu04hu2h3q5ud3ki15v2o1ld2ojj7ero.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseauth',
  );
}
